# Generated by Django 5.1 on 2024-09-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_author_record_artist_remove_record_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='genre',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
