# Generated by Django 5.1 on 2024-09-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_record_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='genre',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
