# Generated by Django 5.1.1 on 2024-09-27 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_record_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='store.record')),
            ],
        ),
    ]
